### GET /
GET http://localhost:8080 HTTP/1.1

### POST /auth/register
POST http://localhost:8080/auth/register HTTP/1.1
Content-Type: application/json

 {  "first_name": "lol",
  	"email": "lolf@gmail.com",
  	"password": "Nejc123!",
  	"confirm_password": "Nejc123!"
}

### POST /auth/login
POST http://localhost:8080/auth/login HTTP/1.1
Content-Type: application/json

{
  	"email": "lolf@gmail.com",
  	"password": "Nejc123!"
}

### GET /auth
GET http://localhost:8080/auth HTTP/1.1

### POST /auth/signout
POST http://localhost:8080/auth/signout HTTP/1.1

### PATCH /users/:id
PATCH http://localhost:8080/users/c6b07375-27a6-4667-a1a8-fcfb95fefba1 HTTP/1.1
Content-Type: application/json

{
  	"role_id": "1212c428-fc69-46c1-b549-e13302d0e19f"
}

### GET /orders
GET http://localhost:8080/orders HTTP/1.1

### GET /orders/chart
GET http://localhost:8080/orders/chart HTTP/1.1

### GET /users
GET http://localhost:8080/users HTTP/1.1


### GET /permissions
GET http://localhost:8080/permissions

### POST /permissions
POST http://localhost:8080/permissions HTTP/1.1
Content-Type: application/json

{
  	"name": "edit_permissions"
}

### GET /roles
GET http://localhost:8080/roles HTTP/1.1

### DELETE /roles/:id
DELETE http://localhost:8080/roles/0a1966a3-c942-4d06-b65e-7b1c0e59df41 HTTP/1.1

### POST /roles
POST http://localhost:8080/roles HTTP/1.1
Content-Type: application/json

{
  	"name": "Viewer",
    "permissions": ["8db0c951-11d8-4e5b-ae4a-543af5ccc6c8"]
}

### PATCH /roles/:id
PATCH http://localhost:8080/roles/82acbf18-b7cf-4363-b1c1-a76acc8a8579 HTTP/1.1
Content-Type: application/json

{
  	"name": "Admin",
    "permissions": ["8db0c951-11d8-4e5b-ae4a-543af5ccc6c8","797c0953-9e29-444e-bcfd-19b1d227ca90"]
}